---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy: 
    collections:
    - community.general
    - ansible.posix
    - redhat.rhel_system_roles

# prepend_galaxy:
# - RUN _build/configs/ansible.cfg /etc/ansible/ansible.cfg
options:
  package_manager_path: /usr/bin/microdnf


build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'